### ISSUE TITLE
updating this to the latest version causes me to crash on launch

### ISSUE THREAD

**Issue by gravysamich** [xieaoDev/Lollipop#1]
https://pastebin.com/kuhedwvB here is my crash log.

i wanted to use your powah mod but it would also crash on launch so i figure i needed to update lollipop. i was using Lollipop-1.14.4-0.0.4 but updating to Lollipop-1.14.4-0.0.10 causes the crash.

**Comment by owmii** [comment]
This crash Caused by other mod "Charm" by svenhjol
see here: 
    `at svenhjol.charm.base.CharmAsmHooks.handleMusicTick(CharmAsmHooks.java:71) `

This crash report has no trace of my mods.

**Comment by gravysamich** [comment]
it is definitely an issue with your mod. i can use the old version just fine. charm also works just fine. that means something in the updated version has changed. 

i am also just realizing i installed lollipop for countdown which i no longer even have installed. since this old version i am using doesn't support the powah and this new version seems to be incompatible with charm, i guess my only option is to just not use it.

i am gonna also report this to the charm devs i guess since you took the time to point them out.

**Comment by owmii** [comment]
The crash report are clear and the only problem is the method `CharmAsmHooks.handleMusicTick` frome "Charm" mod returns null result.
You should report that to him. 
Charm issue tracker link: https://github.com/svenhjol/Charm/issues

Also my mod is not present in the crash report.

**Comment by gravysamich** [comment]
https://i.imgur.com/yyNt0b3.png - proof your mod is installed. this is the newest version too as i was hoping you had fixed the error.

https://pastebin.com/EMig4S2b - the crash report from the image above.

look, i am not saying it is only your mod and that charm has nothing to do with the crash. i am just saying, i have 180+ mods that all work fine with charm. every one of my mods work, but if i install lollipop i crash on start up.

the simple fact of the matter is, the game launches fine with charm. as soon as i install your mod, it no longer starts.

however, i fixed it on my own. it had nothing to do with charm. it was the version of forge i was using. forge-28.1.92 was what i was using. i installed the latest version and it started up right away. i even installed just lollipop and charm and it worked perfectly fine. 

you might want to make a note somewhere to use forge-28.1.96.

**Comment by owmii** [comment]
Forge should warn you if you need to upgrade and not to crash :(
Bdw, Thanks for reporting.
