### ISSUE TITLE
Capability implementation is wrong

### ISSUE THREAD

**Issue by pupnewfster** [xieaoDev/Lollipop#6]
https://github.com/owmii/Lollipop/blob/1.16/src/main/java/owmii/lib/block/AbstractEnergyStorage.java#L76-L101 If you read the docs on getCapability and also LazyOptional#invalidate you will see that this implementation is incorrect. You are not supposed to be returning a new lazy optional each time, and you are supposed to invalidate it when it is no longer valid (such as when the tile unloads).

**Comment by owmii** [comment]
Oh! Thanks, I will find some way to use the `Direction` parameter without executing multiple `LazyOptional `instances.
Sorry for the late reply!! :[
